server:
  port: 5687
  servlet:
    context-path: /api

wx:
  appid: wx88ec10cc0c160814
  secret: cbfcc94f31462c0f5881eb5d5d455a68

spring:
  application:
    name: creep-vocab
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL 8 connection string
    url: jdbc:mysql://${DB_HOST:139.224.27.132}:${DB_PORT:3306}/creep_vocab?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:endless@028btc}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  
  data:
    redis:
      host: ${REDIS_HOST:139.224.27.132}
      port: ${REDIS_PORT:6379}
      database: 0
      password: endless@028btc

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.creepvocab: debug
